### ISSUE TITLE
Duplicate changes sent from client

### ISSUE THREAD

**Issue by chengfred** [Simperium/simperium-android#112]
MC Log of history of note changes:

`/pb/4ddf/` - version, time, clientid, change['sv'], change['v']['content']

From version 10 onwards, the client is sending changes with the same `sv`, the server is dutifully merging these with the changes it has already gotten, resulting in duplicates of all of those lines.

It appears as if, client is either not getting the resulting change server so it can't update it's ghost data and corresponding `sv` value. The changes that are generated then are based on a stale ghost and incorporate previous changes already processed.

**Comment by roundhill** [comment]
I still understand about `50%` of what's going on here, but I think it has to do with the client not requesting the full object in a certain scenario:
1. Client is offline and makes a change.
2. Another online client makes a change and syncs.
3. Client connects, but is unable to apply the remote change diff at this line: https://github.com/Simperium/simperium-android/blob/develop/Simperium/src/main/java/com/simperium/client/RemoteChange.java#L118. A new ghost is not created and so the SV stays the same.
4. Now when the client sends a change, it will keep sending the same data plus whatever has been modified locally since then, using the same old SV each time.
5. When the change is applied and acknowledged, the client appears to silently fail here because its SV has fallen behind and it gets stuck in a rut: https://github.com/Simperium/simperium-android/blob/develop/Simperium/src/main/java/com/simperium/client/Channel.java#L1332

From some testing it appears to fix it for me to have the client request the full object again if we reach that exception.

@beaucollins maybe we can get together next week sometime to hash this out.

**Comment by roundhill** [comment]
We've got a plan of attack. Thanks for the help @fredrocious and @beaucollins.
1. If we catch a `RemoteChangeInvalidException` for an acknowledged change, we should remove any localChanges we have in the queue. Essentially move this code to a finally and add a loop that removes local changes for that object in the exception block: https://github.com/Simperium/simperium-android/blob/0395f6644d0516623a65ca0527d8a8dcd9fe3554/Simperium/src/main/java/com/simperium/client/Channel.java#L1319
2. If we have local modifications when updating the ghost, we should attempt to merge them with the newly received ghost. There's a TODO here that marks where this should go: https://github.com/Simperium/simperium-android/blob/0395f6644d0516623a65ca0527d8a8dcd9fe3554/Simperium/src/main/java/com/simperium/client/Bucket.java#L467
