### ISSUE TITLE
Clientids should be persisted with pending changes

### ISSUE THREAD

**Issue by chengfred** [Simperium/simperium-android#56]
From examination of changes we have, this is a gist of top 10 sorted by # of duplicate ccid's and lists the corresponding set of clientids:

https://gist.github.com/fredrocious/7684946

From @mikejohnstn https://github.com/Simperium/simperium-android/blob/18d373eae1ae874da74dbd596c1b6b9cb0dc4b17/Simperium/src/main/java/com/simperium/android/AndroidClient.java#L36

Seems to suggest clientid is generated on each session, not sure if that is used with operations that are still in pending queue

Changing the clientid and resending an operation that has already been processed by the server will currently result in a duplicate as changes are uniquely identified by clientid+ccid

**Comment by beaucollins** [comment]
The random session id portion is not necessary so it can be removed. I had originally added it because two different clients running with the same client id will both receive errors that originate from either client.

The bucket change processor also now ignores errors with ccid's that it didn't send so it shouldn't be a problem.

I suppose another option is generating the session id based on the username or storing the session id in a local preference so it connects with the same one every time.

**Comment by mikejohnstn** [comment]
iOS now stores the ID in a local preference, which was a quick/easy fix.

**Comment by beaucollins** [comment]
@mikejohnstn does the iOS client include a version number in the session id as well, or is it just something like:

`simperium-ios-SESSION`

**Comment by mikejohnstn** [comment]
Not really a "session" id anymore since it's persisted between sessions, but uh...no, it doesn't have a version number, but does have an agent (for Mac/iOS): https://github.com/Simperium/simperium-ios/commit/99d6187aa24fac75614fbbda06b2ef876c55970f

There's also a library identifier and version identifier sent when the channel inits: https://github.com/Simperium/simperium-ios/blob/54b4384cc76a9996b0031b34278f68bd06e1a20d/Simperium/SPWebSocketInterface.m#L144

**Comment by beaucollins** [comment]
Yeah I have the library identifier already. With e85d596 the client will now send something like `android-TOKEN`.
