### ISSUE TITLE
Send full object when diff is invalid

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#63]
Two scenarios for change response:
- [x] Response is 405, send the entire object since `sv` is unknown.
- [x] Response is 440, send full object since diff could not be applied by the server

Full object JSON should be in the `d` field of the change json object payload.

**Comment by beaucollins** [comment]
I'm just going to send the full object to prevent data loss:

> Bad version, client referencing a wrong or missing sv. This is a potential data
> loss scenario: server may not have enough history to resolve conflicts. Client
> has two options:
> - re-load the entity (via e command) then overwrite the local changes
> - send a change with full object (which will overwrite remote changes, history
>   will still be available) referencing the current sv

@fredrocious when recovering from a "405 Invalid Version" and sending the full object data, should I still attempt to send an `sv` or does simperium not care what the `sv` is when also sending the full data in key `d`?

**Comment by chengfred** [comment]
When sending the full data in key `d`, the server essentially just recomputes the diff for you based on your `d` and `sv`

Thinking about it now, this will work fine if the reason you need to send `d` is because there was some error in computing diff clientside (maybe emoji or something), but if the reason is because the server is missing the `sv` data - not sure, I'll look into it on server side.

I think the right thing is for the client to send `sv` anyways, and it should be up to server to do the appropriate thing based on if `sv` is available or not. 

Purposefully omitting the `sv` perhaps should mean to overwrite whatever is current with this data.

**Comment by beaucollins** [comment]
So it would seem reasonable to omit the `sv` if we're responding to a 405 error since the server already told us it doesn't know about that `sv`.

**Comment by chengfred** [comment]
Yeah, I agree, looking at the code just now, it should respond the same currently if you omit or not anyways.

**Comment by beaucollins** [comment]
Can I reuse the same `ccid` or do I need to generate a new one when re-sending the change with the full object data?

**Comment by chengfred** [comment]
Reuse, since it hasn't actually been processed
