### ISSUE TITLE
Merge local modifications when remote object is re-downloaded

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#82]
Scenario:

1) Client A opens note X
2) Client A goes "offline"
3) Client A makes modification and saves note X but change isn't sent
4) Client B makes changes to note X
5) Client A comes online
6) Client B made enough changes to force Client A to "re-download the entity"
7) Client A updates its ghost with latest vresion
8) Client A sends out new change from step 3 that overwrites all note content

While there is no data loss (the revision is recoverable) it is still not ideal.

Client A should be able to produce the delta from the local version to the re-downloaded object and the apply a three way merge.

**Comment by chengfred** [comment]
If the reason re-download is happening in step 6 is because client sent `cv:xxx` and server responded with `cv:?`, the change from A may still be accepted (individual object history != bucket history)

If re-download is because change from A submitted and server responded with error (405) then I think you're right we have (locally) the original ghost state, from remote, the new ghost state, and the local mods.

Using existing jsondiff semantics we could make step 6/7 smarter:

When redownloading new state (instead of getting changes), check if this object has local mods
If so, transform existing local mods vs. ghost changes

LG = local ghost (the version server doesn't have anymore, and the one our local mods are based off of)
SG = server ghost (the newly downloaded version)

GD = diff(LG, SG) - the delta between our local ghost and the newly downloaded ghost

LD = local mods off of LG (the diff we sent that was rejected, because server no longer has LG)

LD' = transform(LD, GD, LG) - transform local diff (LD) vs ghost diff (GD) based on original state LG

Send LD' (now = diff based on SG) instead of LD

Which effectively does the 3 way merge

**Comment by beaucollins** [comment]
Sticking with current implementation of handling a 405
